[package]
name = "wasm-reader"
version = "0.1.0"
authors = ["Jonathan Soo <jcsoo@agora.com>"]

[dependencies]
wasm-leb128 = {path = "../wasm-leb128" }
byteorder = { version = "1", default-features = false }